# DuckDB数据库配置
duckdb:
  # 离线特征存储数据库
  offline_db_path: "/workspace/data/quant_features.duckdb"
  
  # 实时特征处理数据库
  realtime_db_path: "/workspace/data/realtime_features.duckdb"
  
  # 数据库配置参数
  config:
    threads: 4
    memory_limit: "2GB"
    max_memory: "4GB"
    
  # 表配置
  tables:
    raw_ohlc: "raw.ohlc_data"
    features: "main.features_ohlc_technical"
    realtime_features: "main.realtime_features"
    
# 数据源配置
data_sources:
  # 历史数据文件路径
  historical_data_path: "/workspace/data/raw/"
  
  # Arrow IPC文件路径
  arrow_cache_path: "/workspace/data/arrow_cache/"
  
  # 支持的数据格式
  supported_formats: ["csv", "parquet", "arrow", "json"]