# RuleGo决策引擎配置

server:
  port: "8080"
  read_timeout: 30
  write_timeout: 30

feast:
  base_url: "http://localhost:6566"  # Feast serving地址
  use_mock: true  # 是否使用模拟客户端（测试用）
  trading_pairs:
    - "BTCUSDT"
    - "ETHUSDT"
    - "ADAUSDT"
    - "DOTUSDT"

trading:
  update_interval: 30  # 决策更新间隔（秒）
  rules_file: "/workspace/decision_engine/rules/trading_rules.json"

# 日志配置
logging:
  level: "info"
  format: "json"
  
# 风险管理配置
risk_management:
  max_position_size: 0.1  # 最大仓位比例
  stop_loss_ratio: 0.02   # 止损比例
  take_profit_ratio: 0.05 # 止盈比例
  max_daily_trades: 10    # 每日最大交易次数