# RuleGo决策引擎配置
server:
  port: "8080"
  read_timeout: 30
  write_timeout: 30

feast:
  base_url: "http://localhost:6566"
  use_mock: true  # 暂时使用模拟客户端
  trading_pairs:
    - "BTCUSDT"
    - "ETHUSDT"

trading:
  update_interval: 5  # 秒
  rules_file: "/workspace/decision_engine/rules/trading_rules.json"

logging:
  level: "info"
  file: "/workspace/logs/decision_engine.log"